version: '3.8'
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=CafeCRM
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
  flywayOrders:
    image: flyway/flyway:latest
    container_name: orders-flyway
    command: migrate -url=jdbc:postgresql://postgres:5432/CafeCRM  -user=admin -password=secret -schemas=Orders
    volumes:
      - ./flyway/sql/orders:/flyway/sql/orders
    depends_on:
      - postgres
  flywaySecurity:
    image: flyway/flyway:latest
    container_name: security-flyway
    command: migrate -url=jdbc:postgresql://postgres:5432/CafeCRM  -user=admin -password=secret -schemas=Security
    volumes:
      - ./flyway/sql/security:/flyway/sql/security
    depends_on:
      - postgres

