version: '3.8'
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=CafeCRM
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
  flyway:
    image: flyway/flyway:latest
    container_name: my-flyway
    command: migrate -url=jdbc:postgresql://postgres:5432/CafeCRM  -user=admin -password=secret -schemas=Orders
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgres

